name: vv20 CI Pipeline

on:
  push:
    branches:
      - main  # or the branch you want to monitor
  #workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            repository: vinod812/vv20
            token: ${{ secrets.GITHUB_TOKEN }}  # Ensures access to private repositories if needed

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Change to your Java version
          distribution: 'zulu'

      # Step 3: Build the project
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Configure AWS credentials for S3 upload
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA5FCD6LO3KIOJ6LLE
          aws-secret-access-key: JHAnUxipH6t/MaoMrpuNvPgDykeKXKMxfQ6rnt97
          aws-region: us-east-2  # Replace with your AWS region

      # Step 5: Upload the WAR file to S3
      - name: Upload WAR file to S3
        run: |
          aws s3 cp target/*.war s3://vvawsbucket/vvapp.war

      # Step 4: Upload the WAR file as an artifact (optional)
      #- name: Upload WAR file
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: my-war-file
      #    path: target/*.war
